### ISSUE TITLE
USER STORY: Make use of a Image Carousel to display links for recipes

### ISSUE THREAD

**Issue by Owen-Gibbs** [Owen-Gibbs/snap-dish#7]
As a: USER 

I can: CLICK ON THE CAROUSEL IMAGE 

So that: I CAN VIEW DIFFERENT RECIPES

# ACCEPTANCE CRITERIA

* Carousel will display images for different categories
* can click on each link to view recipes
* Recipes have prep time, ingredients, instructions and cooking tips 
* Carousel is responsive for different screen sizes

# TASKS

- [x] Develop a carousel
- [x] Source high quality images
- [x] Make all images link to correct recipes
- [x] Design pages for all recipes
- [x] include the relevant information on recipe pages (prep time, ingredients, instructions and (optional) cooking tips)
