### ISSUE TITLE
USER STORY: About page and contact from

### ISSUE THREAD

**Issue by Owen-Gibbs** [Owen-Gibbs/snap-dish#8]
As a: USER

I can: SEE CONTACT INFO ON THE ABOUT PAGE

So that: I CAN MAKE CONTACT IF NEEDED

# ACCEPTANCE CRITERIA

* About page is accessible in the menu 
* About page will have a contact form
* contact form will have a submit button
* Form will be responsive

# TASKS

- [ ] Develop an about page
- [ ] Design a form
- [ ] Style form with CSS
- [ ] Make form responsive for all devices
